//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFautosalon.BD_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class АвтосалонEntities2 : DbContext
    {
        private static АвтосалонEntities2 _context;
        public АвтосалонEntities2()
            : base("name=АвтосалонEntities2")
        {

        }

        public static АвтосалонEntities2 GetContext_()
        {
            if (_context == null) _context = new АвтосалонEntities2();
            return _context;

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Комплектации> Комплектации { get; set; }
        public virtual DbSet<Место_на_складе> Место_на_складе { get; set; }
        public virtual DbSet<Модели_ТС> Модели_ТС { get; set; }
        public virtual DbSet<Опции> Опции { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<ПТС> ПТС { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Склад> Склад { get; set; }
        public virtual DbSet<Строка_Комплектации> Строка_Комплектации { get; set; }
        public virtual DbSet<ТС> ТС { get; set; }
    }
}
