//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFautosalon.BD_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int Уид { get; set; }
        public int Клиент { get; set; }
        public string ТС { get; set; }
        public string Пункт_Назначения { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual ТС ТС1 { get; set; }
    }
}
