//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFautosalon.BD_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Место_на_складе
    {
        public int Уид { get; set; }
        public int Склад { get; set; }
        public string Тип_Ячейки { get; set; }
        public string Содержимое { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Склад Склад1 { get; set; }
        public virtual ТС ТС { get; set; }
    }
}
