//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFautosalon.BD_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТС
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТС()
        {
            this.Заказы = new HashSet<Заказы>();
            this.Место_на_складе = new HashSet<Место_на_складе>();
        }
    
        public string Птс { get; set; }
        public int Модель { get; set; }
        public int Комплектация { get; set; }
        public Nullable<decimal> Цена { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
        public virtual Комплектации Комплектации { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Место_на_складе> Место_на_складе { get; set; }
        public virtual Модели_ТС Модели_ТС { get; set; }
        public virtual ПТС ПТС1 { get; set; }
    }
}
